services:
    techxuexi:
        image: cnlomou/xuexitech:1.4
        container_name: techxi-wechat
        restart: on-failure
        volumes:
            - ./xuexi:/xuexi/user
        ports:
            - 16666:8088
            - 16667:80
        shm_size: 2gb
        environment:
            - CRONTIME=10 18,0 * * *
            - Pushmode=6
            - ZhuanXiang=True
            - Scheme=
            - MaxWorkers=2
